### PR TITLE
Fix preview urls

### PR DESCRIPTION
**Pull request by ravichdev**
- Fixes preview URLs to point to WP siteurl so it can generate the token and redirect the user to the correct FE URL.
- Conditionally load wp-grahql to allow wp-graphql be installed and activated as a separate plugin
- Fix an undefined index notice

### CODE REVIEW

**Comment by chriszarate** [comment]
Thanks for this PR, @ravichdev! I'm confused why this first change is necessary:

> Fixes preview URLs to point to WP siteurl so it can generate the token and redirect the user to the correct FE URL

[This code](https://github.com/Automattic/vip-decoupled-bundle/blob/trunk/preview/preview.php#L40) hooked into `template_redirect` should accomplish the same thing without the need to filter the preview URL. Is that code not running or not working for you?

**Comment by ravichdev** [comment]
@chriszarate [This code](https://github.com/Automattic/vip-decoupled-bundle/blob/trunk/preview/preview.php#L40) actually does redirect to the correct Frontend Preview URL, but if a site home_url is set to a different URL the preview URLs in wp-admin also seem to use that URL.

In my local setup, the frontend is at http://localhoost:3000 and the WP is at http://wordpress.test, and I set the "Home URL" option in settings to http://localhost:3000. In the wp-admin posts screen or the block editor preview button, the preview URL is now using the home url i.e http://localhost:3000/?p=POST_ID&preview=true. This would need to be http://wordpress.test/?p=POOST_ID&preview=true for the `template_redirect` hook to work and [this change](https://github.com/Automattic/vip-decoupled-bundle/pull/59/files#diff-5facbf52abbd6dfca1fb33ed1c9a05990eef68410236441e4037f72ea3a22126R63-R71) updates that.

Let me know if you are not seeing this behaviour and I can see if there is an issue on my local only

**Comment by chriszarate** [comment]
> In my local setup, the frontend is at http://localhoost:3000 and the WP is at http://wordpress.test, and I set the "Home URL" option in settings to http://localhost:3000. In the wp-admin posts screen or the block editor preview button, the preview URL is now using the home url i.e http://localhost:3000/?p=POST_ID&preview=true. This would need to be http://wordpress.test/?p=POOST_ID&preview=true for the `template_redirect` hook to work and [this change](https://github.com/Automattic/vip-decoupled-bundle/pull/59/files#diff-5facbf52abbd6dfca1fb33ed1c9a05990eef68410236441e4037f72ea3a22126R63-R71) updates that.


Hi @ravichdev, apologies for the delay. I was having a lot of trouble reproducing this until I realized you must not be using our Next.js boilerplate. The README calls out that preview functionality requires this, but it could be better emphasized. I've addressed that in #63.

You might be interested in the additional information added in that PR around what is done by our Next.js boilerplate to complete the preview implementation. It is relatively straightforward and could be adopted by any framework.

**Comment by ravichdev** [comment]
Hi @chriszarate That seems to solve the issue, thank you for updating the docs.

**Pull request closed without merging**
